config/routes.rb
VPB::Application.routes.draw do
  resources :wysihat_files

  get 'admin_console' => 'admins#index'
  get 'admin_accept_user_invitation' => 'admins#accept_user_invitation'
  patch 'admin_accept_user_invitation' => 'admins#accept_user_invitation'
  get 'my_video_papers' => 'video_papers#my_video_papers'
  get 'my_shared_video_papers' => 'video_papers#shared_video_papers', :as => :shared_video_papers
  get 'test_exception' => 'home#test_exception'

  if Rails.env.test?
    # check if the name of this is login_for_test???
    get 'login_for_test/:id' => 'users#login_for_test'
  end

  get 'video_papers/report' => 'video_papers#report'
  get 'video_papers/user/:user' => 'video_papers#index', :as => :user_video_papers
  resources :video_papers do
    member do
      get 'share'
      patch 'shared'
      get 'unshare'
      get 'edit_section'
      patch 'update_section'
      get 'edit_section_duration'
      patch 'update_section_duration'
      get 'publish'
      get 'unpublish'
      get 'transcoding_status'
    end
    resources :videos do
      member do
        post 'start_transcoding_job'
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "authentications" }
  devise_for :admins, :controllers => { :registrations => "registrations" }
  root :to => 'home#index'
  resources :admins
  resources :users

  get 'about/' => 'home#about', :as => :about

  get 'contact/' => 'home#contact', :as => :contact

  get 'help_videos/:video_name' => 'home#help_videos', :as => :help_video

  post 'sns/transcoder_update' => 'sns#transcoder_update'

  get 'preflight' => 'home#preflight'

  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'
end

app/views/admins/accept_user_invitation.html.erb
<div class="content_details bg_change">
  <div class="top_curv">
    <div class="bottom_curv">
      <div class="admin_panel">
        <h2>Accept the invitation of <%= @user.first_name %> <%= @user.last_name %> (<%= @user.email %>)</h2>

        <%= form_for @user, :url => admin_accept_user_invitation_url, :html => { :method => :patch } do |f| %>
          <%= f.error_messages %>
          <%= f.hidden_field :id %>

          <p><%= f.label :password %></p>
          <div class="input_bg">
            <p><%= f.password_field :password %></p>
          </div>

          <p><%= f.label :password_confirmation %></p>
          <div class="input_bg">
            <p><%= f.password_field :password_confirmation %></p>
          </div>

          <div class="button">
            <p><%= f.submit "Submit",:class=>"login_btn" %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<div class="content_details">
  <div class="top_curv">
    <div class="bottom_curv">
      <div class="admin_panel">
        <h3>Administrative Users.</h3>
        <% @admins.each do |admin|%>
          <% unless admin == current_admin %>
            <p><%= admin.name%> | <%= mail_to admin.email%> | <%= link_to "Remove", admin, data: {:confirm => 'Are you sure?'}, :method => :delete %></p>
          <% else %>
            <p><%= admin.name %> | This is you. </p>
          <% end %>
        <% end %><br/>
        <h3>Normal Users. <%= link_to "(CSV report)", users_url(:format => :csv) %></h3>
        <% @users.each do |user| %>
          <!-- FIXME: the link to change a users password used to be generated with -->
          <% # link_to "Set Password", :controller=>"passwords",:action=>"edit",:reset_password_token=>user.generate_reset_password_token! %>
          <!-- but this wasn't working with the latest devise -->
          <p><%= user.name %> | <%= mail_to user.email %> | <%= link_to "Edit", edit_user_path(user) %> | <%= link_to "Remove", user, data: {:confirm => 'Are you sure?'}, :method => :delete %>
            <% if user.invited_to_sign_up? %>
              | <%= link_to "Accept Invitation", admin_accept_user_invitation_url(:user_id => user.id) %>
            <% else %>
              | <%= link_to "Video Papers", user_video_papers_path(user) %>
            <% end %>
            </p>
        <% end %>
      </div>
    </div>
  </div>
</div>