config/routes.rb
VPB::Application.routes.draw do
  resources :wysihat_files

  get 'admin_console' => 'admins#index'
  get 'admin_accept_user_invitation' => 'admins#accept_user_invitation'
  patch 'admin_accept_user_invitation' => 'admins#accept_user_invitation'
  get 'my_video_papers' => 'video_papers#my_video_papers'
  get 'my_shared_video_papers' => 'video_papers#shared_video_papers', :as => :shared_video_papers
  get 'test_exception' => 'home#test_exception'

  if Rails.env.test?
    # check if the name of this is login_for_test???
    get 'login_for_test/:id' => 'users#login_for_test'
  end

  get 'video_papers/report' => 'video_papers#report'
  get 'video_papers/user/:user' => 'video_papers#index', :as => :user_video_papers
  resources :video_papers do
    member do
      get 'share'
      patch 'shared'
      get 'unshare'
      get 'edit_section'
      patch 'update_section'
      get 'edit_section_duration'
      patch 'update_section_duration'
      get 'publish'
      get 'unpublish'
      get 'transcoding_status'
    end
    resources :videos do
      member do
        post 'start_transcoding_job'
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "authentications" }
  devise_for :admins, :controllers => { :registrations => "registrations" }
  root :to => 'home#index'
  resources :admins
  resources :users

  get 'about/' => 'home#about', :as => :about

  get 'contact/' => 'home#contact', :as => :contact

  get 'help_videos/:video_name' => 'home#help_videos', :as => :help_video

  post 'sns/transcoder_update' => 'sns#transcoder_update'

  get 'preflight' => 'home#preflight'

  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'
end

app/models/video_paper.rb
class VideoPaper < ActiveRecord::Base
  #Class variables
  @@per_page = 5

  ###################################
  # Associations
  ###################################
  belongs_to :user, :foreign_key=> "owner_id"
  has_many :sections, :dependent => :destroy
  has_one :video, :dependent => :destroy
  has_many :shared_papers, :dependent => :destroy
  has_many :users, -> { distinct }, :through=>:shared_papers

  ###################################
  # Validations
  ###################################
  validates_presence_of :title
  validates_presence_of :owner_id
  validates_presence_of :status

  ###################################
  # Callbacks
  ###################################
  after_create :construct_video_paper_sections

  ##################################
  # instance methods
  ##################################

  attr_reader :per_page

  # Public Methods
  def format_created_date
    created_at = self.created_at
    created_at.strftime("%A %B #{created_at.day.ordinalize}, %Y")
  end

  def published?
    self.status == "published"
  end

  def publish!
    self.status = "published"
    save!
  end
  ##
  # The one controller action that shares
  def share(shared_paper_params)
    retval = false
    shared_paper = SharedPaper.new(shared_paper_params)
    shared_paper.video_paper = self
    if shared_paper.save
      # TODO: look into `deliver_later` mail strategy
      ShareMailer.share_email(shared_paper.user,shared_paper.video_paper,self.user,shared_paper.notes).deliver_now
      retval = true
    end
    retval
  end

  def unpublished?
    self.status == "unpublished"
  end

  def unpublish!
    self.status = "unpublished"
    save!
  end

  def unshare(user_id)
    retval = false
    user = User.find(user_id)

    unless user.nil?
      paper = self.shared_papers.find_by_user_id(user.id)
      retval = true if paper && paper.destroy
    end
    retval
  end

  def video_status
    if video
      if video.private?
        "Private"
      else
        "Public"
      end
    else
      "No video uploaded"
    end
  end

  ##################################
  # Class methods
  ##################################

  class << self
    def order_by(order_by_param)
      case order_by_param
        when 'title_desc'
          'title DESC'
        when 'title_asc'
          'title ASC'
        when 'date_asc'
          'created_at ASC'
        when 'date_desc'
          'created_at DESC'
      else
        'created_at DESC'
      end
    end

  end
# Protected Methods
protected

  def construct_video_paper_sections
    logger.debug("\nConstructing sections for video paper id: #{self.id.to_s} \n\n")

    ::Settings.sections.each do |section_setting|
      section = Section.new
      section.video_paper = self
      section.title = section_setting[1]["title"]
      section.save
    end

    logger.debug("\nFinished constructing sections for video paper id: #{self.id.to_s} \n\n")
  end

end

app/controllers/video_papers_controller.rb
require 'will_paginate/array'

class VideoPapersController < ApplicationController
  before_action :authenticate_any_user!, :except=>[:new,:create,:show,:transcoding_status]
  before_action :authenticate_user!, :only=>[:new,:create]
  before_action :authenticate_owner!, :only=>[:edit,:edit_section,:update,:update_section,:share,:edit_section_duration,:update_setion_duration,:publish,:unpublish,:destroy]
  before_action :authenticate_shared!, :only=>[:show]
  before_action :authenticate_admin!, :only=>[:index, :report]
  helper_method :owner_or_admin?
  helper_method :owner?

  def index
      order_by = VideoPaper.order_by(params[:order_by])
      if params[:user]
        user = User.find(params[:user].to_i)
        @video_papers = user.my_video_papers.paginate(:page=>params[:page], :per_page=>10).order(order_by)
      else
        @video_papers = VideoPaper.order(order_by).page(params[:page]).per_page(10)
      end
  end

  # report that can be pasted from html to google docs
  def report
    rows = [["id", "title", "paper update time", "author", "paper status",  "video update time", "video length",
       "video private?", "shared with" ]]
    VideoPaper.all.each{|paper|
      rows << [
        paper.id, paper.title, paper.updated_at, paper.user.name, paper.status,
        paper.video ? paper.video.updated_at : "",
        paper.video ? paper.video.duration : "",
        paper.video ? paper.video.private : "",
        paper.users.map{|u|u.name}.join(', ')
        ]
    }
    render :plain => rows.map{|row|row.join("\t")}.join("<br>")
  end

  def my_video_papers
    order_by_sql = VideoPaper.order_by(params[:order_by])
    if current_user
      @video_papers = current_user.my_video_papers.paginate(:page=>params[:page], :per_page=>5).order(order_by_sql)
    else
      # this can hapen if an admin is logged in and they aren't also logged in as a user
      @video_papers = [].paginate
    end
  end

  def shared_video_papers
    order_by_sql = VideoPaper.order_by(params[:order_by])
    @video_papers = current_user.video_papers.paginate(:page=>params[:page], :per_page=>8).order(order_by_sql)
  end

  def show
    @video_paper = VideoPaper.find(params[:id])
    @sections = @video_paper.sections
    @video = @video_paper.video

    if @video_paper.unpublished?  && !owner_or_admin?
      redirect_to shared_video_papers_path, :notice=>"this video paper is currently not published."
    end
  end

  def new
    @video_paper = VideoPaper.new
    @video_paper.user = current_user
  end

  def edit
    @video_paper = VideoPaper.find(params[:id])
    @video = @video_paper.video
  end

  def edit_section
    @video_paper = VideoPaper.find(params[:id])
    @section = @video_paper.sections.find_by_title(params[:section])
    @video = @video_paper.video

    # if the section can't be found by title, then use the first
    if @section == nil
      @section = @video_paper.sections.first
    end
  end

  def create
    # support create without params
    if params.has_key?(:video_paper)
      @video_paper = VideoPaper.new(video_paper_params(params[:video_paper]))
      if current_user
        @video_paper.user = current_user
      end

      if @video_paper.save
        case params[:commit]
          when "Enter in notes"
            redirect_to(@video_paper, :notice => "VideoPaper '#{@video_paper.title}' was successfully created.")
          when "Upload a video"
            redirect_to(new_video_paper_video_path(@video_paper),:notice=>"VideoPaper '#{@video_paper.title}' was succesfully created.")
          end
      else
        render :action => "new"
      end
    else
      render :action => "new"
    end
  end

  def update
    @video_paper = VideoPaper.find(params[:id])
    if @video_paper.update(video_paper_params(params[:video_paper]))
      case params[:commit]
        when "Enter in notes"
          redirect_to(@video_paper, :notice => 'VideoPaper was successfully updated.')
        when "Upload a video"
          redirect_to(new_video_paper_video_path(@video_paper),:notice=>'VideoPaper was succesfully updated.')
        when "Change video"
          redirect_to(edit_video_paper_video_path(@video_paper, @video_paper.video),:notice=>'VideoPaper was succesfully updated.')
        else
          render :action => "edit"
        end
    else
      render :action => "edit"
    end
  end

  def update_section
    @video_paper = VideoPaper.find(params[:id])
    @section = @video_paper.sections.find_by_title(params[:section][:title])
    @section.content = params[:section][:content]
    @section.save!
    #Redirect user to the section they just updated
    #TODO: is there a better way to incorporate dom_friend here?
    case params[:commit]
      when "Edit Timing"
        redirect_to(:controller=>"video_papers",:action=>"edit_section_duration",:section=>@section.title)
        #render "edit_section_duration"
    else
      @edited_section_url = url_for(@video_paper) + "#" + dom_friend(:id=>@section.title)
      redirect_to(@edited_section_url, :notice => 'VideoPaper was successfully updated.')
    end
  end

  def unshare
    @video_paper = VideoPaper.find(params[:id])
    @shared_users = @video_paper.shared_papers
    if @video_paper.unshare(params[:user_id])
      respond_to do |format|
        format.js do
          render 'update_shared_user_block'
        end
        # TODO: remove when I figure out why cucumber tests after rails 4 upgrade aren't sending some requests as js/xhr
        format.html do
          render 'update_shared_user_block'
        end
      end
    else
      redirect_to share_video_paper_path(@video_paper), :notice=> "ruh-roh"
    end
  end

  def destroy
    @video_paper = VideoPaper.find(params[:id])
    @video_paper.destroy
    redirect_to(my_video_papers_url,:notice=>'VideoPaper was successfully destroyed.')
  end

  def share
    @video_paper = VideoPaper.find(params[:id])
    @shared_users = @video_paper.shared_papers
    @share = SharedPaper.new(params[:shared_paper])
    render :layout=> 'lightbox'
  end

  def shared
    @video_paper = VideoPaper.find(params[:id])
    @shared_users = @video_paper.shared_papers
    @share = SharedPaper.new(shared_paper_params(params[:shared_paper]))

    shared_paper = params[:shared_paper]
    #massage the attributes into an acceptable format for the share method
    user = User.find_by_email(params[:shared_paper][:user_id])
    unless user.nil?
      shared_paper[:user_id] = user.id
    end
    @share = @video_paper.share(shared_paper_params(shared_paper))
    if @share
      #redirect_to share_video_paper_path(@video_paper),:notice=>"Great Success!"
    else
      #render "share"
    end

    respond_to do |format|
      format.js do
        render 'update_shared_user_block'
      end
      # TODO: remove when I figure out why cucumber tests after rails 4 upgrade aren't sending some requests as js/xhr
      format.html do
        render 'update_shared_user_block'
      end
    end
  end

  def edit_section_duration
    @video_paper = VideoPaper.find(params[:id])
    @section = @video_paper.sections.find_by_title(params[:section])
    @video = @video_paper.video

    # if the section can't be found by title, then use the first
    if @section == nil
      @section = @video_paper.sections.first
    end

    render :layout => "lightbox"
  end

  def update_section_duration
    @video_paper = VideoPaper.find(params[:id])
    @section = @video_paper.sections.find_by_id(params[:section].delete(:id))
    @video = @video_paper.video

    if @section.update(section_params(params[:section]))
      redirect_to(video_paper_path(@video_paper) + "#" + dom_friend(:id=>@section.title),:notice=>'Timing successfully updated.')
    else
      redirect_to(video_paper_path(@video_paper) + "#" + dom_friend(:id=>@section.title),:notice=>'Invalid time!')
    end
  end

  def publish
    video_paper = VideoPaper.find(params[:id])
    video_paper.publish!
    redirect_to my_video_papers_url, :notice=> "#{video_paper.title} was sucessfully published!"
  end

  def unpublish
    video_paper = VideoPaper.find(params[:id])
    video_paper.unpublish!
    redirect_to my_video_papers_url, :notice=> "#{video_paper.title} was sucessfully unpublished!"
  end

  def transcoding_status
    video_paper = VideoPaper.find(params[:id])
    @video = video_paper.video
    @duration = @video && @video.aws_transcoder_first_submitted_at != nil ? Time.now.to_i - @video.aws_transcoder_first_submitted_at.to_i : 0

    respond_to do |format|
      format.js do
        render 'transcoding_status'
      end
    end
  end

  protected

  def authenticate_owner!
    unless owner_or_admin?
      redirect_to(root_path, :notice => "You aren't authorized for this action.")
    end
  end
  def authenticate_shared!
    video = VideoPaper.find(params[:id])
    unless owner_or_admin? || video.users.include?(current_user)
      unless current_user
        authenticate_user!
      else
        redirect_to(new_user_session_path, :notice=>"You not permitted to view this page.")
      end
    end
  end
  def owner_or_admin?
    admin? || owner?
  end
  def admin?
   admin_signed_in?
  end
  def owner?
    current_user == VideoPaper.find(params[:id]).user
  end

  private

  def video_paper_params(_params)
    params = _params
    params.permit(:title)
  end

  def section_params(_params)
    params = _params
    params.permit(:video_start_time, :video_stop_time)
  end

  def shared_paper_params(_params)
    params = _params
    params.permit(:user_id, :notes)
  end
end

app/helpers/video_papers_helper.rb
module VideoPapersHelper

  ##
  # gets the paperclip thumbnail if it's there, otherwise uses aws.
  #
  def get_video_paper_thumbnail(video_paper)
    unless video_paper.video.nil?
      if video_paper.video.thumbnail?
        image_tag(video_paper.video.thumbnail.url(:thumb), alt: "Thumbnail")
      else
        thumbnail_url = video_paper.video.generate_signed_thumbnail_url()
        if thumbnail_url
          "<img src='#{thumbnail_url}' onerror='this.src=\"#{image_path('blank_fallback.png')}\"' onabort='this.src=\"#{image_path('blank_fallback.png')}\"'/>".html_safe
        else
          "<div class=\"no-thumbnail\"></div>".html_safe
        end
      end
    else
      "<div class=\"no-video\"></div>".html_safe
    end
  end

  def get_video_paper_thumbnail_with_default(video_paper, default_img_url)
    unless video_paper.video.nil?
      if video_paper.video.thumbnail?
        image_tag(video_paper.video.thumbnail.url(:thumb), alt: "Thumbnail")
      else
        thumbnail_url = video_paper.video.generate_signed_thumbnail_url()
        if thumbnail_url
          "<object data='#{thumbnail_url}' type='image/png'>#{image_tag(default_img_url)}</object>".html_safe
        else
          image_tag(default_img_url)
        end
      end
    else
      image_tag(default_img_url)
    end
  end

  def edit_section_link(args)
    video_paper = args[:video_paper]
    section = args[:section]
    text = args[:text]
    return "<a href=\"#{video_paper.id}/edit_section?section=#{section}\" title=\"Edit #{section} Section\">#{text} #{section}</a>"
  end

  def is_last?(counter)
    "last" if counter % 4 == 0
  end

  def pick_arrow(order_by_clause,options={})
    if options[:position] == "top"
      if params[:order_by] == order_by_clause
        image_tag('top_arrow_active.gif')
      else
        image_tag('top_arrow_normal.gif')
      end
    else
      if params[:order_by] == order_by_clause
        image_tag('bottom_arrow_active.gif')
      else
        if params[:order_by].nil? && order_by_clause == 'date_desc'
          image_tag('bottom_arrow_active.gif')
        else
          image_tag('bottom_arrow_normal.gif')
        end
      end
    end
  end
end

app/views/video_papers/_shared_users.html.erb
<div id="messages">
  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :class => "#{name} msg" %>
  <%- end -%>
</div>
<div id="user-shared">
<% unless @shared_users.empty? %>
  <h4>Shared With:</h4>
	<ul>
    <% @shared_users.each do |shared_user| %>
    	  <li>
    	    <h5><%= shared_user.user.name%></h5>
    	    <p><%= shared_user.user.email%></p>
    	    <a title="unshare" class="unshare" href="<%= unshare_video_paper_path(@video_paper)-%>?user_id=<%=shared_user.user_id-%>">unshare</a>
        </li>
    <% end %>
	</ul>
<% end %>
</div>

<script type="text/javascript">
  // resize the modal when the content has changed.
  $j.fancybox.resize()  
</script>

app/views/video_papers/edit_section_duration.html.erb
<div class="modal_video_wrapper">
  <script type="text/javascript">
  VPB.SectionTimeData = [];
  <% @video_paper.sections.each_with_index do |section, index| %>
  VPB.SectionTimeData[<%=index-%>] =
  {
    length:<%= @video_paper.video.duration.nil? ? 0 : @video_paper.video.duration-%>,
    start:<%= section.video_start_time.blank?     ? 0 : section.video_start_time-%>,
    stop:<%= section.video_stop_time.blank?       ? (@video_paper.video.duration || 0) : section.video_stop_time-%>
  };
  <% end %>
  </script>
<% if @video_paper.video%>
  <%= render :partial=> 'video_embed_duration_modal'%>
<% end %>
<div id="duration_buttons">
  <button id="duration_play" class="highlight_btn" style="width: 100px">Play Range</button>
  <button id="duration_pause" class="highlight_btn" style="width: 100px; display: none;">Pause</button>
  <div id="position_slider"></div>
  <span id="duration_position"></span>
</div>
<div class="select_range_label">
  Select a timing range
</div>
<div id="duration_slider_wrapper">
  <div id="duration_slider"></div>
</div>
<%= form_for @section, :url=> update_section_duration_video_paper_path do |f| %>
<fieldset>
  <%= f.hidden_field :id%>
  <div class="timer_ranges">
    <div class="timer_range">
      <%= f.label :video_start_time, "Start Time (HH:MM:SS)"%>
      <%= f.text_field :video_start_time,:value=> @section.to_timestamp(@section.video_start_time.blank? ? 0 : @section.video_start_time)  %>
    </div>
    <div class="timer_range">
      <%= f.label :video_stop_time, "Stop Time (HH:MM:SS)"%>
      <%= f.text_field :video_stop_time,:value=> @section.to_timestamp(@section.video_stop_time.blank? ? (@video_paper.video.duration || 0) : @section.video_stop_time)  %>
    </div>
  </div>

  <div class="button">
    <%= f.submit "Save timings",:class=>'highlight_btn'%>
  </div>
</fieldset>
<% end %>
</div>

app/views/video_papers/index.html.erb
<div class="content_details bg_change">
  <div class="top_curv">
    <div class="bottom_curv">
      <div class="my_video_papers">
        <div class="sort">
          <p>
            <strong>Sort by: Title</strong>
            <span class="margin">
              <%= link_to pick_arrow("title_asc",:position=>"top"), {:controller=>"video_papers",:action=>"index",:order_by=>'title_asc'} %>
              <%=link_to pick_arrow("title_desc") ,{:controller=>"video_papers",:action=>"index",:order_by=>'title_desc'} %>
            </span>
            <strong>Date</strong>
            <span>
              <%=link_to pick_arrow("date_asc",:position=>"top"), {:controller=>"video_papers",:action=>"index",:order_by=>'date_asc'}%>
              <%=link_to pick_arrow("date_desc"), video_papers_path %>
            </span>
          </p>
        </div>
        <h1 style="margin-left:15px">Listing all Video Papers</h1>

          <% @video_papers.each do |video_paper| %>
            <div class="video_row">
              <div class="span-4">
                <div class="photo"><a href="<%= video_paper_path(video_paper) %>"><%= get_video_paper_thumbnail(video_paper)%></a></div>
              </div>
              <div class="details">
                <h3><%= video_paper.title %></h3>
                <p>
                  <strong>Author:</strong> <%= video_paper.user.name%>,
                  <strong>Created:</strong> <%= video_paper.format_created_date %><br/>
                  <strong>Paper Status:</strong> <%= video_paper.status.titlecase%>,
                  <strong>Video Status:</strong> <%= video_paper.video_status%><% if admin_signed_in? %>,
                    <strong>Transcoder Status:</strong> <%= video_paper.video && video_paper.video.aws_transcoder_state ? video_paper.video.aws_transcoder_state.titleize : 'Unknown' %>,
                    <%= link_to 'Video Info', [video_paper, video_paper.video] %>
                  <% end %>
                </p>
                <ul>
                  <li class="view_edit_btn"><span><%= link_to 'View', video_paper %> <%= link_to 'Edit', edit_video_paper_path(video_paper) %> <a class="sharing_btn" href="<%= share_video_paper_path(video_paper) %>" class="last">Sharing</a></span></li>
                  <% if video_paper.published? %>
                    <li class="unpublish_btn"><span><%=link_to "Unpublish", unpublish_video_paper_path(video_paper)%></span></li>
                  <% else%>
                    <li class="unpublish_btn"><span><%= link_to "Publish",publish_video_paper_path(video_paper)%></span></li>
                    <li class="unpublish_btn"><span><%= link_to 'Remove', video_paper, data: {:confirm => 'Are you sure?'}, :method => :delete , :title => "Remove" %></span></li>
                  <%end%>
                </ul>
              </div>
            </div>
          <% end %>
            <div class="paging"><ul><%= will_paginate @video_papers,
              :next_label=> image_tag('next_arrow.gif'),
              :previous_label=>image_tag('pre_arrow.gif')%></ul></div>

          </div>
      </div>
    </div>
  </div>
</div>

app/views/video_papers/my_video_papers.html.erb
<div class="content_details bg_change">
  <div class="top_curv">
    <div class="bottom_curv">
      <div class="my_video_papers">
        <div class="sort">
          <p>
            <strong>Sort by: Title</strong>
            <span class="margin">
              <%= link_to pick_arrow("title_asc",:position=>"top"), {:controller=>"video_papers",:action=>"my_video_papers",:order_by=>'title_asc'} %>
              <%=link_to pick_arrow("title_desc") ,{:controller=>"video_papers",:action=>"my_video_papers",:order_by=>'title_desc'} %>
            </span>
            <strong>Date</strong>
            <span>
              <%=link_to pick_arrow("date_asc",:position=>"top"), {:controller=>"video_papers",:action=>"my_video_papers",:order_by=>'date_asc'}%>
              <%=link_to pick_arrow("date_desc"), my_video_papers_path %>
            </span>
          </p>
        </div>
        <% @video_papers.each do |video_paper| %>
          <div id="<%=video_paper.title.downcase.gsub(" ","-")%>" class="video_row">
            <div class="span-4">
              <div class="photo"><a href="<%= video_paper_path(video_paper) %>"><%= get_video_paper_thumbnail(video_paper)%></a></div>
            </div>
            <div class="details">
              <h3><%= video_paper.title %></h3>
              <p><strong>Created:</strong> <%= video_paper.format_created_date %><br/>
              <strong>Paper Status:</strong> <%= video_paper.status.titlecase%>,
              <strong>Video Status:</strong> <%= video_paper.video_status%></p>
              <ul>
                <li class="view_edit_btn"><span><%=link_to "View",video_paper_path(video_paper)%> <%= link_to "Edit",edit_video_paper_path(video_paper)%> <a class="sharing_btn" href="<%= share_video_paper_path(video_paper) %>" class="last">Sharing</a></span></li>
                <% if video_paper.published? %>
                  <li class="unpublish_btn"><span><%=link_to "Unpublish", unpublish_video_paper_path(video_paper)%></span></li>
                <% else%>
                  <li class="unpublish_btn"><span><%= link_to "Publish",publish_video_paper_path(video_paper)%></span></li>
                  <li class="unpublish_btn"><span><%= link_to 'Remove', video_paper, data: {:confirm => 'Are you sure?'}, :method => :delete , :title => "Remove" %></span></li>
                <%end%>
              </ul>
            </div>
          </div>
        <% end %>
        <div class="paging"><ul><%= will_paginate @video_papers,
          :next_label=> image_tag('next_arrow.gif'),
          :previous_label=>image_tag('pre_arrow.gif')%></ul></div>

      </div>
      <span class="clear"></span> </div>
  </div>
</div>

app/views/video_papers/show.html.erb
<script type="text/javascript">
VPB.SectionTimeData = [];
<% @video_paper.sections.each_with_index do |section, index| %>
VPB.SectionTimeData[<%=index-%>] =
{
  start:<%= section.video_start_time.blank?    ? 0 : section.video_start_time-%>,
  stop:<%= section.video_stop_time.blank?      ? 0 : section.video_stop_time-%>

};
<% end %>
<% unless @video_paper.video.nil? || !@video_paper.video.transcoded? %>
VPB.video = true;
<% end %>
</script>

<div class="content_details bg_change">
  <div class="top_curv">
    <div class="bottom_curv">
      <div class="view_video">
        <h2><%=@video_paper.title%>
          <% if owner_or_admin? %>
            <%= link_to image_tag('big_pencil_icon.png'),edit_video_paper_path(@video_paper)%>
          <% end %>
        </h2>
        <div class="produced_content">
          <p>Produced by <%=h @video_paper.user.name%>, <%= @video_paper.format_created_date %></p>
          <% if @video_paper.video.nil? %>
            <div class="no-video"></div>
            <% if owner_or_admin? %>
              <p class="upload_btn" style="margin-left: 115px;"><%= link_to 'Upload video', new_video_paper_video_path(@video_paper) %></p>
            <% end %>
          <% else %>
            <div class="video"><%= render :partial=>'video_embed' %></div>
            <% if owner_or_admin? %>
              <p class="upload_btn"><%= link_to 'Change video', edit_video_paper_video_path(@video_paper, @video_paper.video) %></p>
            <% end %>
          <% end %>
        </div>
        <div class="inner_blue_tab">
          <div id="tabs" class="top_tab">
            <ul>
              <% @video_paper.sections.each_with_index do |section, index| %>
                <li id="<%= dom_friend :id => section.title %>_tab" class="tab">
                  <a href="#<%= dom_friend :id => section.title %>">
                    <span><%= section.title %>
                      <% if owner_or_admin? %>
                        <img class="edit-button" id="edit_<%= dom_friend :id => section.title %>" title="Edit <%=section.title-%> Section" src="/images/small_pencil_icon.png" />
                      <%- end -%>
                    </span>
                  </a>
                </li>
              <% end %>
            </ul>
            <% @video_paper.sections.each_with_index do |section, index| %>
              <div class="tab_content" id="<%= dom_friend :id => section.title %>">
                <%= form_for section, :url => update_section_video_paper_path(@video_paper) do |f| %>
                  <div class="into_content">
                    <div class="section-content content-border">
                      <%=section.content ? section.content.html_safe : ''%>
                    </div>

                    <% if owner_or_admin? %>
                      <div class="section-editor content-border">
                        <%= hidden_field :section, :title, :value=> section.title %>
                        <%= f.text_area :content, :class => "tinymce", :id => "section_#{section.id}_content", :rows => 19 %>
                        <div class="edit-section-toolbar">
                          <%= submit_tag "Save",:id => "save-"+dom_friend(:id => section.title), :class => 'highlight_btn' %>
                          <a href="#" class="cancel-button">Cancel</a>
                          <% # This is disabled until it works better %>
                          <% unless @video_paper.video.nil? || !@video_paper.video.transcoded? %>
                            <%= link_to "Edit Timing",
                              {
                                :controller=>"video_papers",
                                :action=>"edit_section_duration",
                                :section=> section.title,
                              },
                              :class=>"timing-button"-%>
                          <% end%>
                        </div><!-- edit-section-toolbar -->
                      </div><!-- section-editor -->
                    <% end # owner_or_admin %>
                  </div>
                <% end # edit form %>
              </div>
            <% end %>
          </div>
          <%# initialize tinymce just once for the page%>
          <%= tinymce :width => 500, :height => 260, :setup => "VPB.sectionEditor.tinyMceInit" %>
        </div>
      </div>
      <span class="clear"></span>
  </div>
</div>