config/routes.rb
VPB::Application.routes.draw do
  resources :wysihat_files

  get 'admin_console' => 'admins#index'
  get 'admin_accept_user_invitation' => 'admins#accept_user_invitation'
  patch 'admin_accept_user_invitation' => 'admins#accept_user_invitation'
  get 'my_video_papers' => 'video_papers#my_video_papers'
  get 'my_shared_video_papers' => 'video_papers#shared_video_papers', :as => :shared_video_papers
  get 'test_exception' => 'home#test_exception'

  if Rails.env.test?
    # check if the name of this is login_for_test???
    get 'login_for_test/:id' => 'users#login_for_test'
  end

  get 'video_papers/report' => 'video_papers#report'
  get 'video_papers/user/:user' => 'video_papers#index', :as => :user_video_papers
  resources :video_papers do
    member do
      get 'share'
      patch 'shared'
      get 'unshare'
      get 'edit_section'
      patch 'update_section'
      get 'edit_section_duration'
      patch 'update_section_duration'
      get 'publish'
      get 'unpublish'
      get 'transcoding_status'
    end
    resources :videos do
      member do
        post 'start_transcoding_job'
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "authentications" }
  devise_for :admins, :controllers => { :registrations => "registrations" }
  root :to => 'home#index'
  resources :admins
  resources :users

  get 'about/' => 'home#about', :as => :about

  get 'contact/' => 'home#contact', :as => :contact

  get 'help_videos/:video_name' => 'home#help_videos', :as => :help_video

  post 'sns/transcoder_update' => 'sns#transcoder_update'

  get 'preflight' => 'home#preflight'

  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" type="image/x-icon" href="/images/favicon.png" />
<title>VideoPaperBuilder</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <!--[if IE 6]>
  <script type="text/javascript" src="/javascripts/jq-png-min.js"></script>
  <script type="text/javascript" src="/javascripts/png.js"></script>
  <![endif]-->
  <%= analytics_init if GoogleAnalytics.valid_tracker? %>
</head>
<body>
<div id="wrapper">
  <div id="main">
    <div id="cover">
      <div id="header">
        <div id="menu">
          <div class="left_curve">
            <div class="right_curve">
              <ul>
                <li><a href="/about">About VPB</a></li>
                <li class="last"><a href="https://concord.org/" title="The Concord Consortium">The&nbsp;Concord&nbsp;Consortium</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="logo_login">
          <div class="logo"><a href="/" title="VideoPaper Builder&reg;"><img src="/images/logo.gif" alt="VideoPaper Builder&reg;"  /></a></div>
          <%- unless @hide_login_form %>
            <% if user_signed_in? %>
              <div class="logout">
                <%= render :partial =>'sessions/login'%>
              </div>
            <% else %>
              <div class="login">
                <%= render :partial =>'sessions/login'%>
              </div>
            <% end %>
          <%- end %>
        </div>
      </div>
      <div id="messages">
        <%- flash.each do |name, msg| -%>
          <%= content_tag :div, msg, :class => "#{name} msg" %>
        <%- end -%>
      </div>
      <div id="body_container">
        <div id='browser_not_supported'>
          <%# this div is replace with a message in application.js if the browser is not supported #%>
          <noscript>
            <div id='inner_browser_not_supported'>
              Please enable Javascript in your browser to use this site.
            </div>
          </noscript>
        </div>
        <div id="inner_container"<%= ' class=full' if @full_width_page %>>
        <% if admin_signed_in? %>
          <div class="tabs">
            <ul>
              <%= content_tag :li, link_to(raw("<span>Admin Console</span>"),admin_console_path) %>
              <%= content_tag :li, link_to(raw("<span>Invite a new user</span>"), new_user_invitation_path) %>
              <%= content_tag :li, link_to(raw("<span>Invite a new admin</span>"),new_admin_invitation_path) %>
              <%= content_tag :li, link_to(raw("<span>All Video Papers</span>"),video_papers_path) %>
              <%= content_tag :li, link_to(raw("<span>Admin Logout</span>"), destroy_admin_session_path, :method => :delete) %>
            </ul>
          </div>
        <% elsif user_signed_in? %>
          <div class="tabs">
            <ul>
              <%= content_tag :li, link_to(raw("<span>Authoring</span>"), new_video_paper_path),:class=>is_active?("new") || is_active?("edit")%>
              <%= content_tag :li, link_to(raw("<span>My VideoPapers</span>"),my_video_papers_path),:class=>( is_active?("my_video_papers") || my_paper?)%>
              <%= content_tag :li, link_to(raw("<span>Shared With Me</span>"),shared_video_papers_path),:class=>(is_active?("shared_video_papers") || shared_paper?)%>
            </ul>
          </div>
        <% end %>
        <%= yield%>
        </div>
      </div>
    </div>
  </div>
  <div id="footer">
    <div class="footer_inner">
      <div class="col1">
        <h3>VideoPaper Builder<span class="reg">&reg;</span></h3>
        <ul>
          <li><a href="/" title="VideoPaper Builder&reg;">VPB Home</a></li>
          <li><a href="/about" title="About VideoPaper Builder&reg;">About VPB</a></li>
          <li><a href="/contact" title="Contact the Concord Consortium">Contact Us</a></li>
        </ul>
      </div>
      <div class="col2">
        <h3>The Concord Consortium</h3>
        <ul>
          <li><a href="https://concord.org/" title="The Concord Consortium">Home</a></li>
          <li><a href="https://concord.org/blog/" title="The Concord Consortium Blog">Blog</a></li>
          <li><a href="https://concord.org/our-work/research-projects/" title="The Concord Consortium's Projects">Our Work</a></li>
          <li><a href="https://concord.org/our-work/publications/" title="The Concord Consortium's Publications">Publications</a></li>
          <li><a href="https://concord.org/about" title="About the Concord Consortium">About Us</a></li>
        </ul>
      </div>
      <div id="cc-logo">
        <a href="https://concord.org/" title="The Concord Consortium"><img src="/images/cc-logo.png" alt="The Concord Consortium" /></a>
      </div>
    </div>
  </div>
  </div>
</body>
</html>

app/views/layouts/help_videos.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" type="image/x-icon" href="/images/favicon.png" />
<title>VideoPaperBuilder</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
</head>
<body class="help">
  <div id="wrapper">
    <%= yield%>
    <p id="close"></p>
  </div>

  <script type="text/javascript">
  $j(function() {
    $j('#close').html('<a href="#" onclick="window.close(); return false;">close this window</a>')
  });
  </script>
</body>
</html>

app/views/layouts/lightbox.html.erb
<%= yield %>